version: '3'

services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    environment:
      PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ./:/app
      - ./.env:/app/src/.env
  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local